# Iris Shell — app-level ProGuard rules.
# Module-level consumer rules live alongside each module's build.gradle.kts.
#
# See AGENT.md §410 — confirm versions against libs.versions.toml before
# adding library-specific keep rules.

# General
-dontwarn org.jetbrains.annotations.**
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes EnclosingMethod
-keepattributes InnerClasses

# Hilt — https://dagger.dev/hilt/hilt-gradle-plugin
# Hilt's KSP-additive keep rules are auto-included; nothing to add manually.
-keep class com.iris.irisshell.data.** { *; }
-keep class com.iris.irisshell.agent.** { *; }
-keep class com.iris.irisshell.terminal.** { *; }
-keep class com.iris.irisshell.ssh.** { *; }
-keep class com.iris.irisshell.ui.** { *; }
-keep class com.iris.irisshell.design.system.** { *; }
-dontwarn com.iris.irisshell.**
-dontwarn com.termux.**
-dontwarn com.iris.irisshell.ui.terminal.TerminalViewModel_HiltModules**
-dontwarn com.iris.irisshell.ui.**Kt

# Room — auto-generated by Room's bundled rules via the `room` plugin.

# kotlinx.serialization — auto-included by the serialization plugin.

# SSHJ / BouncyCastle — runtime crypto classes referenced via reflection
-keep class org.bouncycastle.** { *; }
-dontwarn org.bouncycastle.**

# OkHttp / Okio — modern OkHttp ships consumer rules, but keep these
# defensively because we depend on SSE + logging interceptors.
-dontwarn okhttp3.internal.**
-dontwarn okio.**

# Termux JNI — native bins are loaded from :terminal module's jniLibs.
-keep class com.termux.** { *; }
-keepclasseswithmembers class * {
    native <methods>;
}
