package com.iris.irisshell.data.block

import android.net.TrafficStats
import android.os.Process
import android.os.SystemClock
import com.iris.irisshell.domain.block.NetworkMetricsCollector
import com.iris.irisshell.domain.block.NetworkSample
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Network metrics collector backed by Android's [TrafficStats].
 *
 * Reads `getUidRxBytes(uid)` / `getUidTxBytes(uid)` — uid is captured at
 * construction (IrisShell's own uid). Captures all traffic generated by
 * the IrisShell process, including PRoot-launched commands (apt, curl,
 * git clone, etc.).
 *
 * Rate is computed as `(current - last) / elapsed_seconds` — clamped to
 * `>= 0` because `TrafficStats` can briefly return smaller values during
 * counter rollover.
 *
 * Sample interval: 500ms (caller's responsibility — see
 * `docs/block-engine/PLAN.md` §3.2).
 *
 * UNTESTED — verify before use.
 */
@Singleton
class TrafficStatsCollector @Inject constructor() : NetworkMetricsCollector {

    private val uid: Int = Process.myUid()
    private var lastRx: Long = TrafficStats.getUidRxBytes(uid)
    private var lastTx: Long = TrafficStats.getUidTxBytes(uid)
    private var lastSampleMs: Long = SystemClock.elapsedRealtime()

    /** Returns the latest network sample and updates internal deltas. */
    override fun sample(): NetworkSample {
        val now = SystemClock.elapsedRealtime()
        val elapsedSec = (now - lastSampleMs).coerceAtLeast(1L) / 1000.0
        val rx = TrafficStats.getUidRxBytes(uid)
        val tx = TrafficStats.getUidTxBytes(uid)
        val rxRate = ((rx - lastRx) / elapsedSec).toLong().coerceAtLeast(0L)
        val txRate = ((tx - lastTx) / elapsedSec).toLong().coerceAtLeast(0L)
        lastRx = rx
        lastTx = tx
        lastSampleMs = now
        return NetworkSample(
            rxRate = rxRate,
            txRate = txRate,
            rxTotal = rx,
            txTotal = tx,
        )
    }

    /** Cumulative bytes since session start (uid-scoped). */
    override fun snapshotTotals(): Pair<Long, Long> =
        TrafficStats.getUidRxBytes(uid) to TrafficStats.getUidTxBytes(uid)
}
