package com.iris.irisshell.domain.block

/**
 * Network traffic sample taken at a point in time.
 *
 * `rxRate`/`txRate` are per-second deltas against the previous sample.
 * `rxTotal`/`txTotal` are cumulative since session start (uid-scoped).
 *
 * Source: Android `TrafficStats.getUidRxBytes(uid)` / `getUidTxBytes(uid)`.
 * Captures all traffic generated by the IrisShell process, including
 * PRoot-launched commands (apt, curl, git clone, etc.).
 */
data class NetworkSample(
    val rxRate: Long,
    val txRate: Long,
    val rxTotal: Long,
    val txTotal: Long,
) {
    val hasTraffic: Boolean get() = rxRate > 0 || txRate > 0
}

/**
 * Cumulative network usage over the lifetime of a single block.
 *
 * `rxBytes`/`txBytes` are the deltas measured between the block's start
 * and its completion (or current moment if still running).
 *
 * The UI uses `hasTraffic` to decide whether to render the network badge
 * — blocks that don't touch the network (e.g. `ls -la`) stay quiet.
 */
data class NetworkDelta(
    val rxBytes: Long,
    val txBytes: Long,
) {
    val hasTraffic: Boolean get() = rxBytes > 0 || txBytes > 0
}

/**
 * Network metrics surface available to `:ui`.
 *
 * Implemented in `:data` over Android's `TrafficStats`. UI consumers
 * receive a domain interface so they stay decoupled from the data
 * layer (per AGENT.md §107-145 layer rules).
 */
interface NetworkMetricsCollector {
    /** Take a fresh sample and return it (updates internal deltas). */
    fun sample(): NetworkSample

    /** Current cumulative RX/TX totals (uid-scoped) without sampling. */
    fun snapshotTotals(): Pair<Long, Long>
}
